"""+column price_for_one

Revision ID: 39fa5b485edc
Revises: 44bc71bd6c50
Create Date: 2025-01-10 20:53:16.082570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39fa5b485edc"
down_revision: Union[str, None] = "44bc71bd6c50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_associations",
        sa.Column(
            "price_for_one", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_associations", "price_for_one")
    # ### end Alembic commands ###
